services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    devices:
      - "/dev/serial0:/dev/serial0"
    environment:
        - PYTHONUNBUFFERED=1
        - SERIAL_PORT=/dev/serial0
        - BAUD_RATE=115200
        - MQTT_TOPIC=rfid/text

  frontend:
    build:
      context: ./Front
      dockerfile: Dockerfile
    ports:
      - "80:3000"